import Head from "next/head";
import NavBar from "./NavBar/NavBar";
import Footer from "./Footer/Footer";

export default function PageLayout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-full h-screen mx-auto bg-gradient-to-tl from-purple-100 to-purple-300">
        <NavBar />
        {children}
        <Footer />
      </main>
    </>
  );
}
